CREATE TABLE Review
(
    REVIEW_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5) NOT NULL,
    PRODUCT_ID NUMBER(5) NOT NULL,
    REVIEW_TEXT VARCHAR2(200) NOT NULL,
    REVIEW_DATE DATE NOT NULL
);




CREATE TABLE Rating
(
    RATING_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5) NOT NULL,
    PRODUCT_ID NUMBER(5) NOT NULL,
    RATING_VALUE NUMBER(1) NOT NULL,
    RATING_DATE DATE NOT NULL
);




INSERT INTO Review VALUES
(1, 108, 101, 'Good quality product', SYSDATE);

INSERT INTO Review VALUES
(2, 224, 102, 'Nice and comfortable', SYSDATE);

INSERT INTO Review VALUES
(3, 567, 103, 'Good fitting and quality', SYSDATE);

INSERT INTO Review VALUES
(4, 108, 104, 'Product is good', SYSDATE);

INSERT INTO Review VALUES
(5, 224, 105, 'Worth the price', SYSDATE);

COMMIT;




INSERT INTO Rating VALUES
(1, 108, 101, 5, SYSDATE);

INSERT INTO Rating VALUES
(2, 224, 102, 4, SYSDATE);

INSERT INTO Rating VALUES
(3, 567, 103, 5, SYSDATE);

INSERT INTO Rating VALUES
(4, 108, 104, 3, SYSDATE);

INSERT INTO Rating VALUES
(5, 224, 105, 4, SYSDATE);

COMMIT;


SELECT PRODUCT_ID,
       REVIEW_ID,
       CUSTOMER_ID,
       REVIEW_TEXT,
       REVIEW_DATE
FROM Review
ORDER BY PRODUCT_ID;


SELECT PRODUCT_ID,
       AVG(RATING_VALUE) AS AVERAGE_RATING
FROM Rating
GROUP BY PRODUCT_ID;



SELECT PRODUCT_ID,
       AVG(RATING_VALUE) AS AVERAGE_RATING
FROM Rating
GROUP BY PRODUCT_ID
HAVING AVG(RATING_VALUE) >= 4;



SELECT PRODUCT_ID,
       COUNT(RATING_ID) AS TOTAL_RATINGS,
       AVG(RATING_VALUE) AS AVERAGE_RATING,
       MAX(RATING_VALUE) AS HIGHEST_RATING,
       MIN(RATING_VALUE) AS LOWEST_RATING
FROM Rating
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_ID;

COMMIT;
