

CREATE TABLE SELLER (
    SELLER_ID   NUMBER(5)       PRIMARY KEY,
    SELLER_NAME VARCHAR2(100)   NOT NULL,
    CONTACT_NO  VARCHAR2(15),
    EMAIL       VARCHAR2(100)
);


CREATE TABLE PRODUCT (
    PRODUCT_ID   NUMBER(5)       PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100)   NOT NULL,
    SELLER_ID    NUMBER(5)       NOT NULL,
    CONSTRAINT FK_PRODUCT_SELLER
        FOREIGN KEY (SELLER_ID) REFERENCES SELLER(SELLER_ID)
);


CREATE TABLE INVENTORY (
    INVENTORY_ID   NUMBER(5)      PRIMARY KEY,
    SELLER_ID      NUMBER(5)      NOT NULL,
    PRODUCT_ID     NUMBER(5)      NOT NULL,
    STOCK_QUANTITY NUMBER(10)     DEFAULT 0 NOT NULL,
    STOCK_STATUS   VARCHAR2(20)   NOT NULL,
    CONSTRAINT FK_INVENTORY_SELLER
        FOREIGN KEY (SELLER_ID) REFERENCES SELLER(SELLER_ID),
    CONSTRAINT FK_INVENTORY_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_INVENTORY_QUANTITY
        CHECK (STOCK_QUANTITY >= 0),
    CONSTRAINT CK_INVENTORY_STATUS
        CHECK (STOCK_STATUS IN ('Available', 'Unavailable'))
);


INSERT INTO SELLER VALUES (1, 'Fashion Hub',   '9876543210', 'fashionhub@example.com');
INSERT INTO SELLER VALUES (2, 'Style Store',   '9876543211', 'stylestore@example.com');
INSERT INTO SELLER VALUES (3, 'Denim World',   '9876543212', 'denimworld@example.com');
INSERT INTO SELLER VALUES (4, 'Shoe Central',  '9876543213', 'shoecentral@example.com');
INSERT INTO SELLER VALUES (5, 'Leather Lane',  '9876543214', 'leatherlane@example.com');


INSERT INTO PRODUCT VALUES (101, 'Floral Dress',   1);
INSERT INTO PRODUCT VALUES (102, 'Casual T-Shirt', 2);
INSERT INTO PRODUCT VALUES (103, 'Slim Fit Jeans', 3);
INSERT INTO PRODUCT VALUES (104, 'Running Shoes',  4);
INSERT INTO PRODUCT VALUES (105, 'Leather Belt',   5);


INSERT INTO INVENTORY VALUES (1001, 1, 101, 25, 'Available');
INSERT INTO INVENTORY VALUES (1002, 2, 102, 0,  'Unavailable');
INSERT INTO INVENTORY VALUES (1003, 3, 103, 15, 'Available');
INSERT INTO INVENTORY VALUES (1004, 4, 104, 0,  'Unavailable');
INSERT INTO INVENTORY VALUES (1005, 5, 105, 30, 'Available');

COMMIT;


SELECT
    S.SELLER_ID,
    S.SELLER_NAME,
    S.CONTACT_NO,
    S.EMAIL,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    I.INVENTORY_ID,
    I.STOCK_QUANTITY,
    I.STOCK_STATUS
FROM SELLER S
JOIN PRODUCT P
    ON P.SELLER_ID = S.SELLER_ID
JOIN INVENTORY I
    ON I.PRODUCT_ID = P.PRODUCT_ID
   AND I.SELLER_ID = S.SELLER_ID
ORDER BY S.SELLER_ID, P.PRODUCT_ID;


SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    STOCK_QUANTITY,
    STOCK_STATUS
FROM PRODUCT P
JOIN INVENTORY I ON I.PRODUCT_ID = P.PRODUCT_ID
ORDER BY PRODUCT_ID;


SELECT
    S.SELLER_NAME,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    I.STOCK_QUANTITY,
    CASE
        WHEN I.STOCK_QUANTITY > 0 THEN 'Available'
        ELSE 'Unavailable'
    END AS AVAILABILITY_STATUS
FROM SELLER S
JOIN PRODUCT P ON P.SELLER_ID = S.SELLER_ID
JOIN INVENTORY I
    ON I.PRODUCT_ID = P.PRODUCT_ID
   AND I.SELLER_ID = S.SELLER_ID
ORDER BY P.PRODUCT_ID;


SELECT
    STOCK_STATUS,
    COUNT(*) AS TOTAL_PRODUCTS
FROM INVENTORY
GROUP BY STOCK_STATUS
ORDER BY STOCK_STATUS;


